### ISSUE TITLE
Exibição das respostas erradas para o exercício.

### ISSUE THREAD

**Issue by mklipe** [mklipe/Thales#10]
Exemplo usando Table e Jquery para ordenar os resultados

http://jsfiddle.net/jsvine/P9SwZ/

**Comment by dmarczal** [comment]
Pode usar tranquilo!

**Comment by mklipe** [comment]
Tabela está funcionando com jquerysorter

Outro exemplo interessante, no final desta página. Usando expand e order. 

http://reconbot.github.com/backbone-tablesorter/demo.html
