### ISSUE TITLE
Criar modelo Dica

### ISSUE THREAD

**Issue by mklipe** [mklipe/Thales#2]
As dicas serão criadas pelos professores. Elas serão úteis para os aprendizes responderem as questões caso estes tenham muitas dificuldades. As dicas serão exibidas de acordo com o número de erros cometidos pelo aprendiz.

**Comment by mklipe** [comment]
Para realizar esta tarefa, deve-se fazer uma adaptação no modelo resposta, para que este guarde também o número de tentativas para uma dada questão.

**Comment by dmarczal** [comment]
1 resposta pode ter n dicas. A dica será apresentada ao aluno depois de um número determinada tentativa. Essa dica sempre será mostrada quando as tentativas forem igual ou maior que o cadastrado pelo professor. Cada tenha mais de uma dica, o processo se dará da seguinte forma:

Dica 1, após 2 erros
Dica 2, após 4 erros

Para o número tentativas 2, 3, será mostrada a dica 1 e para as tentativas iguais ou maiores que 4 a dica 2.

**Comment by dmarczal** [comment]
A quantidade de tentativas está relacionada com a questão a ser respondida e com o aluno que a respondeu. Pode ser feito um modelo separado para isso, ainda que ele será responsável pela lógica necessário por apresentar a dica correta.

**Comment by mklipe** [comment]
Fixed in last commit.
