### ISSUE TITLE
Problema com paginator, ou não..

### ISSUE THREAD

**Issue by mklipe** [mklipe/Thales#8]
Quando é passado 'false' como segundo parâmetro na chamada ao backbone.history.navigate, acontecem alguns problemas como a reescrita de exercícios já exibidos na página e a página ativa não muda no paginator. 

Porém, quando é passado true, funciona perfeitamente, mas dá impressão que a página está sendo toda recarregada

**Comment by mklipe** [comment]
Lendo estes posts:
http://robdodson.me/blog/2012/05/21/exploring-the-backbone-router-and-history-api/ 
http://lostechies.com/derickbailey/2011/08/28/dont-execute-a-backbone-js-route-handler-from-your-code/

**Comment by dmarczal** [comment]
A opção true quer dizer que ele executar novamente a função da url em questão. Com opção false apenas será adicionada a url no browser
